[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sglang"
version = "0.5.3"
description = "SGLang is a fast serving framework for large language models and vision language models."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
]
dependencies = [
  "IPython",
  "aiohttp",
  "anthropic>=0.20.0",
  "blobfile==3.0.0",
  "build",
  "datasets",
  "einops",
  "fastapi",
  "hf_transfer",
  "huggingface_hub",
  "interegular",
  "llguidance>=0.7.11,<0.8.0",
  "modelscope",
  "msgspec",
  "ninja",
  "numpy",
  "openai-harmony==0.0.4",
  "openai==1.99.1",
  "orjson",
  "packaging",
  "partial_json_parser",
  "pillow",
  "prometheus-client>=0.20.0",
  "psutil",
  "py-spy",
  "pybase64",
  "pydantic",
  "python-multipart",
  "pyzmq>=25.1.2",
  "requests",
  "scipy",
  "sentencepiece",
  "setproctitle",
  "soundfile==0.13.1",
  "tiktoken",
  "torch_memory_saver==0.0.9rc2",
  "torchao==0.9.0",
  "tqdm",
  "transformers==4.57.1",
  "uvicorn",
  "uvloop",
  "grpcio==1.75.1", # keep it align with compile_proto.py
  "grpcio-tools==1.75.1", # keep it align with compile_proto.py
  "grpcio-reflection==1.75.1", # required by srt/entrypoints/grpc_server.py
]

[project.optional-dependencies]
decord = ["decord2"]
test = [
  "accelerate",
  "expecttest",
  "gguf",
  "jsonlines",
  "matplotlib",
  "pandas",
  "peft",
  "pytest",
  "sentence_transformers",
  "tabulate",
]
tracing = [
  "opentelemetry-api",
  "opentelemetry-exporter-otlp",
  "opentelemetry-exporter-otlp-proto-grpc",
  "opentelemetry-sdk",
]

rocm630 = [
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp310-cp310-manylinux_2_28_x86_64.whl ; python_version == '3.10'",
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp311-cp311-manylinux_2_28_x86_64.whl ; python_version == '3.11'",
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp312-cp312-manylinux_2_28_x86_64.whl ; python_version == '3.12'",
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp313-cp313-manylinux_2_28_x86_64.whl ; python_version == '3.13'",
    "torch @ https://download.pytorch.org/whl/rocm6.4/torch-2.9.0%2Brocm6.4-cp314-cp314-manylinux_2_28_x86_64.whl ; python_version == '3.14'",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp310-cp310-manylinux_2_28_x86_64.whl ; python_version == '3.10'",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp311-cp311-manylinux_2_28_x86_64.whl ; python_version == '3.11'",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp312-cp312-manylinux_2_28_x86_64.whl ; python_version == '3.12'",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp313-cp313-manylinux_2_28_x86_64.whl ; python_version == '3.13'",
    "torchvision @ https://download.pytorch.org/whl/rocm6.4/torchvision-0.24.0%2Brocm6.4-cp314-cp314-manylinux_2_28_x86_64.whl ; python_version == '3.14'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/pytorch_triton_rocm-3.5.0-cp310-cp310-linux_x86_64.whl ; python_version == '3.10'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/pytorch_triton_rocm-3.5.0-cp311-cp311-linux_x86_64.whl ; python_version == '3.11'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/pytorch_triton_rocm-3.5.0-cp312-cp312-linux_x86_64.whl ; python_version == '3.12'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/pytorch_triton_rocm-3.5.0-cp313-cp313-linux_x86_64.whl ; python_version == '3.13'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/pytorch_triton_rocm-3.5.0-cp314-cp314-linux_x86_64.whl ; python_version == '3.14'",
    "sgl-kernel-rocm630-torch290 @ https://test-files.pythonhosted.org/packages/94/6c/044d1206ac906c4cdac40a806cab3a8a08207e0a79eec84e4555dda9df06/sgl_kernel_rocm630_torch290-0.3.15.post1-cp310-abi3-manylinux2014_x86_64.whl",
    "compressed-tensors",
    "outlines==0.1.11",
    "timm==1.0.16",
    "xgrammar==0.1.25"
]

rocm700 = [
    "torch @ https://download.pytorch.org/whl/nightly/rocm7.0/torch-2.10.0.dev20251011%2Brocm7.0-cp310-cp310-manylinux_2_28_x86_64.whl ; python_version == '3.10'",
    "torch @ https://download.pytorch.org/whl/nightly/rocm7.0/torch-2.10.0.dev20251011%2Brocm7.0-cp311-cp311-manylinux_2_28_x86_64.whl ; python_version == '3.11'",
    "torch @ https://download.pytorch.org/whl/nightly/rocm7.0/torch-2.10.0.dev20251011%2Brocm7.0-cp312-cp312-manylinux_2_28_x86_64.whl ; python_version == '3.12'",
    "torch @ https://download.pytorch.org/whl/nightly/rocm7.0/torch-2.10.0.dev20251011%2Brocm7.0-cp313-cp313-manylinux_2_28_x86_64.whl ; python_version == '3.13'",
    "torch @ https://download.pytorch.org/whl/nightly/rocm7.0/torch-2.10.0.dev20251011%2Brocm7.0-cp314-cp314-manylinux_2_28_x86_64.whl ; python_version == '3.14'",
    "torchvision @ https://download.pytorch.org/whl/nightly/rocm7.0/torchvision-0.25.0.dev20251012%2Brocm7.0-cp310-cp310-manylinux_2_28_x86_64.whl ; python_version == '3.10'",
    "torchvision @ https://download.pytorch.org/whl/nightly/rocm7.0/torchvision-0.25.0.dev20251012%2Brocm7.0-cp311-cp311-manylinux_2_28_x86_64.whl ; python_version == '3.11'",
    "torchvision @ https://download.pytorch.org/whl/nightly/rocm7.0/torchvision-0.25.0.dev20251012%2Brocm7.0-cp312-cp312-manylinux_2_28_x86_64.whl ; python_version == '3.12'",
    "torchvision @ https://download.pytorch.org/whl/nightly/rocm7.0/torchvision-0.25.0.dev20251012%2Brocm7.0-cp313-cp313-manylinux_2_28_x86_64.whl ; python_version == '3.13'",
    "torchvision @ https://download.pytorch.org/whl/nightly/rocm7.0/torchvision-0.25.0.dev20251012%2Brocm7.0-cp314-cp314-manylinux_2_28_x86_64.whl ; python_version == '3.14'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.5.0%2Bgit7416ffcb-cp310-cp310-linux_x86_64.whl ; python_version == '3.10'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.5.0%2Bgit7416ffcb-cp311-cp311-linux_x86_64.whl ; python_version == '3.11'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.5.0%2Bgit7416ffcb-cp312-cp312-linux_x86_64.whl ; python_version == '3.12'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.5.0%2Bgit7416ffcb-cp313-cp313-linux_x86_64.whl ; python_version == '3.13'",
    "pytorch-triton-rocm @ https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.5.0%2Bgit7416ffcb-cp314-cp314-linux_x86_64.whl ; python_version == '3.14'",
    "sgl-kernel-rocm700-torch210 @ https://test-files.pythonhosted.org/packages/aa/69/cd336d660e15884af8f2a829716526ea19ecd1dd826fa3e94f009eeca48f/sgl_kernel_rocm700_torch210-0.3.15.post5-cp310-abi3-manylinux2014_x86_64.whl",
    "compressed-tensors",
    "outlines==0.1.11",
    "timm==1.0.16",
    "xgrammar==0.1.25"
]

[project.urls]
"Homepage" = "https://github.com/sgl-project/sglang"
"Bug Tracker" = "https://github.com/sgl-project/sglang/issues"

[tool.setuptools.package-data]
"sglang" = [
  "srt/layers/moe/fused_moe_triton/configs/*/*.json",
  "srt/layers/quantization/configs/*.json",
  "srt/mem_cache/storage/hf3fs/hf3fs_utils.cpp",
  "srt/speculative/cpp_ngram/*.cpp",
  "srt/speculative/cpp_ngram/*.h",
]

[tool.setuptools.packages.find]
exclude = [
  "assets*",
  "benchmark*",
  "docs*",
  "dist*",
  "playground*",
  "scripts*",
  "tests*",
]

[tool.wheel]
exclude = [
  "assets*",
  "benchmark*",
  "docs*",
  "dist*",
  "playground*",
  "scripts*",
  "tests*",
]

[tool.codespell]
ignore-words-list = "ans, als, hel, boostrap, childs, te, vas, hsa, ment"
skip = "*.json,*.jsonl,*.patch,*.txt"
